// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIl3SMUbBmQG9WwP9T4Zjz7qgJjGPuC7g',
    appId: '1:73322144604:android:0db17e8bc144f5bef51799',
    messagingSenderId: '73322144604',
    projectId: 'neu-spring2022-2',
    storageBucket: 'neu-spring2022-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASRmmikt9hazSscm1KRdxDsXCv9CW49G8',
    appId: '1:73322144604:ios:217abb20ebdadf63f51799',
    messagingSenderId: '73322144604',
    projectId: 'neu-spring2022-2',
    storageBucket: 'neu-spring2022-2.appspot.com',
    iosClientId: '73322144604-l66tm17d6c6t1sfnv6ln6qqf7oshmrok.apps.googleusercontent.com',
    iosBundleId: 'com.example.hyperGarageSale',
  );
}
